### ISSUE TITLE
Incompatible with MATLAB R2021a

### ISSUE THREAD

**Issue by lunkums** [EricMagalhaesDelgado/m2mlapp#1]
The [project page](https://www.mathworks.com/matlabcentral/fileexchange/130069-m2mlapp) on MATLAB File Exchange states that the project's compatibility is:

```
Created with R2023a
Compatible with R2018a to R2023a
```

However, when attempting to use the project in MATLAB R2021a, I get the following errors:

![error](https://github.com/EricMagalhaesDelgado/m2mlapp/assets/42952416/2abeae18-6570-4218-9952-0cc47e3e8f93)

Looks like it's missing some code that was added in recent versions.

**Comment by EricMagalhaesDelgado** [comment]
Thanks @lunkums for your feedback. I did test m2mlapp in R2021b and R2023a releases - I just updated File Exchange compatibility. I put in the backlog of this project to install R2021a and find a way to turn it compatible. I'll let you know.

**Comment by lunkums** [comment]
Much appreciated! Thank you for providing this tool, regardless.
