### ISSUE TITLE
about Rebuilding a broken .MLAPP file

### ISSUE THREAD

**Issue by sunshine-demo** [EricMagalhaesDelgado/m2mlapp#2]
try to rebuild but error below
  Error using util.extractMATFile (line 16)
  Error loading 'test.mlapp'.
it seems like appdesigner.internal.serialization.FileReader doesn`t work with a broken .MLAPP file

**Comment by EricMagalhaesDelgado** [comment]
Depends on how damaged the file is! :)
Sorry it took me a while to get back to this issue. Listen... If you're still facing the problem and are able to share the file, I’d be happy to try and help!
