### ISSUE TITLE
License for m2mlapp?

### ISSUE THREAD

**Issue by flixha** [EricMagalhaesDelgado/m2mlapp#4]
Hi Eric,
thanks a lot for developing m2mlapp, this is a very helpful tool if one wants to batch-edit the source code of several `*.mlapp` files and properly track the changes with git!

I had a look around and would like to contribute two bugfixes for specific cases.

But I was first wondering: do you want m2mlapp to be open source software that others can use? 
If that is the case, it would be very helpful if you can add a license - see, e.g. [licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) and [what-can-i-assume-if-a-publicly-published-project-has-no-license](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

**Comment by EricMagalhaesDelgado** [comment]
Hi Felix! Thank you for your feedback regarding the repository license. I've just added the license file. Feel free to commit any changes directly to the main branch.

**Comment by flixha** [comment]
Great, thanks a lot for adding the license and your quick reply!
