### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by rnwst** [EricMagalhaesDelgado/m2mlapp#5]
Hi Eric,

First off, thank you very much for your excellent work creating `m2mlapp`! There is clearly a lot of demand for turning `.m` files exported via the app designer back into `.mlapp` files for editing with the app designer, and had I not discovered this project, I probably would've attempted to write my own script to do this 😁. I'm sure that this project will quickly gain in popularity, and in anticipation of this I think it might be useful to introduce a style guide to the project to streamline the process of contributing code.

I have used [miss_hit](https://github.com/florianschanda/miss_hit) as a style checker for my own MATLAB code, and can recommend it (unfortunately, MathWorks doesn't provide its own style checker). The configuration file (`miss_hit.cfg`) I use for my own code is as follows (requires `miss_hit` v0.9.44):
```
project_root
suppress_rule: "copyright_notice"
suppress_rule: "unicode"
ignore_dir: "works"

# 75 is the default line length in MATLAB (where the vertical line
# appears).
line_length: 75

# Naming rules - these are inspired by Richard Johnson's MATLAB style
# guidelines (see here for a cheat sheet:
# https://uk.mathworks.com/matlabcentral/fileexchange/45047-matlab-style-guidelines-cheat-sheet).
regex_class_name: "[A-Z][a-zA-Z0-9]*" # upper camelCase
regex_function_name: "[a-z][a-zA-Z0-9]*" # lower camelCase
regex_nested_name: "[a-z][a-zA-Z0-9]*" # lower camelCase
regex_method_name: "[a-z][a-zA-Z0-9]*" # lower camelCase
regex_script_name: "[a-zA-Z0-9_]+" # complete freedom for naming scripts
regex_parameter_name: "[a-z][a-zA-Z0-9]*" # lower camelCase
regex_attribute_name: "[a-z][a-zA-Z0-9]*" # lower camelCase
```

This can also be setup as a GitHub action, so that, for example, every time someone submits a pull request, the check is automatically run.

I would be happy to make the necessary contributions to set this up, but first I'd like to hear your thoughts on this issue.

Cheers,
Nat

**Comment by EricMagalhaesDelgado** [comment]
Hi Nat,
Thanks for your kind words! I wasn't familiar with the miss_hit style checker, but I'll definitely take a closer look soon. I'm afraid I haven't been following those styles so far... :)

But feel free to contribute!

As for m2mlapp, I have used it in the past to recover a few corrupted .mlapp files, but I don’t use it in my daily workflow anymore.

I created a simple script that programmatically exports .m files from .mlapp files, which I run before making any commits. This way, those .m files are included in the project solely for that purpose. Here’s the main part of the script:

```
readerObj = appdesigner.internal.serialization.FileReader([fileBaseName '.mlapp']);
matlabCode = readerObj.readMATLABCodeText();
writematrix(matlabCode, [fileBaseName '_exported.m'], 'FileType', 'text', 'WriteMode', 'overwrite', 'QuoteStrings', 'none');

```
